#!/usr/bin/env bash
# Generates guest/secrets_generated.go from .secrets.env, run as the first
# step of conf.natyv.json's wasm_compile -- TinyGo's `-ldflags -X` does NOT
# actually work for wasip1 builds (verified directly: a spike build
# compiled cleanly but the injected value never landed, confirmed both by
# grepping the binary and by invoking the compiled function via wasmtime),
# so plain generated Go source is the real mechanism instead.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SECRETS_FILE="$ROOT/.secrets.env"
OUT_FILE="$ROOT/guest/secrets_generated.go"

if [ ! -f "$SECRETS_FILE" ]; then
	echo "error: $SECRETS_FILE not found -- run scripts/save-app-password.sh first" >&2
	exit 1
fi

set -a
# shellcheck disable=SC1090
source "$SECRETS_FILE"
set +a

if [ -z "${GMAIL_USERNAME:-}" ] || [ -z "${GMAIL_APP_PASSWORD:-}" ]; then
	echo "error: GMAIL_USERNAME or GMAIL_APP_PASSWORD missing from $SECRETS_FILE" >&2
	exit 1
fi

cat >"$OUT_FILE" <<EOF
// Code generated by scripts/gen-secrets-go.sh from .secrets.env.
// DO NOT EDIT. DO NOT COMMIT (gitignored).
package main

const gmailUsername = "${GMAIL_USERNAME}"
const gmailAppPassword = "${GMAIL_APP_PASSWORD}"
EOF

echo "wrote $OUT_FILE"
